swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get User Account Information
      description: API for retrieving user account information including balance and transactions
      responses:
        '200':
          description: User account information retrieved successfully
          schema:
            $ref: '#/definitions/UserAccountInfo'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    patch:  # Ajout du nouvel endpoint PATCH pour mettre à jour une transaction spécifique
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Transaction Category
      description: API for updating the category of a transaction
      parameters:
        - in: body
          name: body
          description: Update transaction category
          required: true
          schema:
            $ref: '#/definitions/TransactionCategoryUpdate'
      responses:
        '200':
          description: Transaction category updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccountInfo:  # Définition du schéma pour les informations de compte utilisateur
    type: object
    properties:
      balance:
        type: number
        description: User's account balance
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:  # Définition du schéma pour les transactions
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      amount:
        type: number
        description: Transaction amount
      description:
        type: string
        description: Transaction description
  TransactionCategoryUpdate:  # Définition du schéma pour la mise à jour de la catégorie de transaction
    type: object
    properties:
      transactionId:
        type: string
        description: Transaction ID to update
      category:
        type: string
        description: New transaction category
      description:
        type: string
        description: Updated description of the transaction